version: '3.8'

services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    image: synchronize-exact-app
    volumes:
      - .:/app
    command: ["npm", "start"]
